// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace StoreApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240229061137_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.16");

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Book"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Computer"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Monitor"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Oem"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Phone"
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 2,
                            Price = 32500m,
                            ProductName = "Bilgisayar"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Price = 3500m,
                            ProductName = "Klavye"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            Price = 9850m,
                            ProductName = "Monitör"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Price = 2500m,
                            ProductName = "Mouse"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 5,
                            Price = 1500m,
                            ProductName = "Deck"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1,
                            Price = 25m,
                            ProductName = "History"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            Price = 45m,
                            ProductName = "Hamlett"
                        });
                });

            modelBuilder.Entity("Entities.Models.Product", b =>
                {
                    b.HasOne("Entities.Models.Category", "Category")
                        .WithMany("products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.Models.Category", b =>
                {
                    b.Navigation("products");
                });
#pragma warning restore 612, 618
        }
    }
}
